# -*- coding: utf-8 -*-
"""Act1_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlQ_qb9JjE_y0slSMcEMyhgNZhYzeMfG
"""

triangle_area = lambda b, h : ...

triangle_area = lambda b, h :(b*h)/(2)

triangle_area(3,4)

def test_triangle_area():
  assert triangle_area(5,4) == 10
  assert triangle_area(10,20) == 100
  assert triangle_area(10, 10) == 50
  assert triangle_area(10, 0) == 0
  assert triangle_area(5, 10) == 25
test_triangle_area()

def triangle_area(base, height):
    """Computes the area of a triangle given the base and height

    Args:
        base: The base of the triangle
        height: The height of the triangle

    Returns:
        float: The area of the triangle
    """
    output = (base*height)/2
    return output

def test_triangle_area():
  assert triangle_area(5,4) == 10
  assert triangle_area(10,20) == 100
  assert triangle_area(10, 10) == 50
  assert triangle_area(10, 0) == 0
  assert triangle_area(5, 10) == 25
test_triangle_area()

help(triangle_area)